# Generated by Django 5.2.3 on 2025-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('pais', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
